---
output: html_document
---
#Altmetric data analysis
```{r}
#Correlation between Scopus.citations and other variales of the data set
with(altmetrics, cor.test(Scopus.citations, Mendeley.readers))
with(altmetrics, cor.test(Scopus.citations,Tweeters))
with(altmetrics, cor.test(Scopus.citations,Facebook.walls))
with(altmetrics, cor.test(Scopus.citations,Reddit.threads))
with(altmetrics, cor.test(Scopus.citations,Pinterest.posts))
with(altmetrics, cor.test(Scopus.citations, Bloggers))
with(altmetrics, cor.test(Scopus.citations, Peer.review.sites))
with(altmetrics, cor.test(Scopus.citations, Weibo.users))
with(altmetrics, cor.test(Scopus.citations, News.outlets))
with(altmetrics, cor.test(Scopus.citations, Google..authors))
with(altmetrics, cor.test(Scopus.citations, F1000.reviews))
with(altmetrics, cor.test(Scopus.citations, Q.A.site.users))
with(altmetrics, cor.test(Scopus.citations, Policy.documents))
with(altmetrics, cor.test(Scopus.citations, CiteULike.readers))
```

```{r}
with(altmetrics, cor.test(Mendeley.readers,Tweeters))
with(altmetrics, cor.test(Mendeley.readers,Facebook.walls))
with(altmetrics, cor.test(Mendeley.readers,Reddit.threads))
with(altmetrics, cor.test(Mendeley.readers,Pinterest.posts))
with(altmetrics, cor.test(Mendeley.readers, Bloggers))
with(altmetrics, cor.test(Mendeley.readers, Peer.review.sites))
with(altmetrics, cor.test(Mendeley.readers, Weibo.users))
with(altmetrics, cor.test(Mendeley.readers, News.outlets))
with(altmetrics, cor.test(Mendeley.readers, Google..authors))
with(altmetrics, cor.test(Mendeley.readers, F1000.reviews))
with(altmetrics, cor.test(Mendeley.readers, Q.A.site.users))
with(altmetrics, cor.test(Mendeley.readers, Policy.documents))
with(altmetrics, cor.test(Mendeley.readers, CiteULike.readers))
```

```{r}
library(ggplot2)
altmetrics <- read.csv("C:/Users/vinuthna/Desktop/Data_Science/Datasets/Altmetrics.csv", header = TRUE)
```
```{r}
str(altmetrics)
```
```{r}
altmetrics$Cited <- as.factor(altmetrics$Cited)
```
#Variable Impact analysis

```{r}
summary(altmetrics$Journal)
#Visualization for distribution of articles with citations and without citations for each journal
qplot(data = altmetrics, x = Journal, color = Cited, color = I(black))
```

```{r}
#Plot describing how citations recieved by articles changed based on the published year
qplot(x = Scopus.year, data = altmetrics, color = Cited)
#Observation - in the year 2014 % of articles with citations is much less compared to previous years
```

```{r}
#Distribution of Scopus citation count
qplot(data=altmetrics, x=Scopus.citations, binwidth=2) +
  scale_x_continuous(limits = c(0,500), breaks = seq(0,1000,10)) +
  scale_y_continuous(limits = c(0,3000))
```
```{r}
#Distribution of scopus citation count across journal level
qplot(data=altmetrics, x=Scopus.citations, binwidth=2, color = I('blue')) +
  scale_x_continuous(limits = c(0,500), breaks = seq(0,1000,10)) +
  scale_y_log10() +
  facet_wrap(~Journal)
```

```{r}
#Summary of citations at journal level
by(altmetrics$Scopus.citations,altmetrics$Journal,summary)
```
```{r}
summary(log10(altmetrics$Scopus.citations + 1))
```
```{r}
qplot(data=altmetrics, x=Scopus.citations, binwidth=10, color = Journal, geom = 'freqpoly') +
  scale_x_continuous(limits = c(0,500), breaks = seq(0,1000,10)) +
  scale_y_log10()
```

```{r}
qplot(data = altmetrics, x=Journal, y = Scopus.citations,geom = 'boxplot') + scale_y_log10()
```

```{r}
by(altmetrics$Scopus.citations>0,altmetrics$Journal,summary)
```

```{r}
qplot(data=altmetrics, y= Scopus.citations, x=Mendeley.readers)
ggplot(aes(x=Mendeley.readers, y= Scopus.citations), data=altmetrics) + geom_point(alpha = 1/10) +
  scale_x_continuous(limits = c(0,500), breaks = seq(0,500,25)) +
  scale_y_continuous(limits = c(0,900))
```
```{r}
qplot(data=altmetrics, y= Scopus.citations, x=Mendeley.readers)
ggplot(aes(x=Mendeley.readers, y= Scopus.citations), data=altmetrics) + geom_jitter(alpha = 1/10) +
  scale_x_continuous(limits = c(0,100), breaks = seq(0,100,10)) +
  scale_y_continuous(limits = c(0,900))
```
```{r}
qplot(data=altmetrics, x=Mendeley.readers, y=Tweeters) +
  scale_x_continuous(limits = c(0,600), breaks = seq(0,600,40))
```

```{r}
qplot(data=altmetrics, x=Mendeley.readers, y=Tweeters) +
  scale_x_continuous(limits = c(0,600), breaks = seq(0,600,40))
```
```{r}
ggplot(aes(x=Mendeley.readers, y=Tweeters), data = altmetrics) +
  geom_point(alpha = 1/20) +
  xlim(0,600) +
  coord_trans(y = 'sqrt')
```

```{r}
qplot(data=altmetrics, y= Scopus.citations, x=Mendeley.readers)
```
```{r}
library(dplyr)
```
```{r}
#Mendely readers impact on citation count analysis
Mendeley_groups <- group_by(altmetrics, Mendeley.readers)
altmetrics.CiCnt_by_MenCnt <- summarise(Mendeley_groups, 
                              citation_count_mean = mean(Scopus.citations),
                              citation_count_median = median(Scopus.citations),
                              n = n())
altmetrics.CiCnt_by_MenCnt <- arrange(altmetrics.CiCnt_by_MenCnt,Mendeley.readers)
head(altmetrics.CiCnt_by_MenCnt)
ggplot(aes(x = Mendeley.readers,citation_count_mean), data = altmetrics.CiCnt_by_MenCnt) + geom_line()
#Facebook walls impact on citation count analysis
Facebook_groups <- group_by(altmetrics, Facebook.walls)
altmetrics.Cicnt_by_FB <- summarise(Facebook_groups, 
                          citation_count_mean = mean(Scopus.citations),
                          citation_count_meadian = median(Scopus.citations),
                          n = n())
head(altmetrics.Cicnt_by_FB)
ggplot(aes(Facebook.walls, citation_count_mean), data = altmetrics.Cicnt_by_FB) +
  geom_line()
#Tweets impact on citation count analysis  
Twitter_groups <- group_by(altmetrics, Tweeters)
altmetrics.Cicnt_by_Tweets <- summarise(Twitter_groups, 
                          citation_count_mean = mean(Scopus.citations),
                          citation_count_meadian = median(Scopus.citations),
                          n = n())
head(altmetrics.Cicnt_by_Tweets)
ggplot(aes(Tweeters, citation_count_mean), data = altmetrics.Cicnt_by_Tweets) +
  geom_line()
News_groups <- group_by(altmetrics, News.outlets)
altmetrics.Cicnt_by_News <- summarise(News_groups, 
                          citation_count_mean = mean(Scopus.citations),
                          citation_count_meadian = median(Scopus.citations),
                          n = n())
head(altmetrics.Cicnt_by_News)
ggplot(aes(News.outlets, citation_count_mean), data = altmetrics.Cicnt_by_News) +
  geom_line()
CiteULike_groups <- group_by(altmetrics, CiteULike.readers)
altmetrics.Cicnt_by_CiteULike <- summarise(CiteULike_groups, 
                          citation_count_mean = mean(Scopus.citations),
                          citation_count_meadian = median(Scopus.citations),
                          n = n())
head(altmetrics.Cicnt_by_CiteULike)
ggplot(aes(CiteULike.readers, citation_count_mean), data=altmetrics.Cicnt_by_CiteULike) +
  geom_line()
```
```{r}
ggplot(aes(x=Mendeley.readers, y=Scopus.citations), data = altmetrics) +
  coord_cartesian(xlim = c(0,200), ylim = c(0,1000))+
  geom_point(alpha = 1/20, position = position_jitter(h=0), color = 'orange') +
  geom_line(stat = 'summary', fun.y=mean) +
  geom_line(stat = 'summary', fun.y = quantile, fun.args =list(probs = .1), linetype = 2, color = 'MediumPurple') +
  geom_line(stat = 'summary', fun.y = quantile, fun.args =list(probs = .5), color = 'red') +
  geom_line(stat = 'summary', fun.y = quantile, fun.args =list(probs = .9), linetype = 2, color = 'green')
```


```{r}
ggplot(aes(x=CiteULike.readers, y=Scopus.citations), data=altmetrics) +
  geom_point()
```
```{r}
ggplot(aes(x=Bloggers, y=Scopus.citations), data=altmetrics) +
  geom_point()
```

```{r}
ggplot(aes(x=F1000.reviews, y=Scopus.citations), data=altmetrics) +
  geom_point()
```








